name: Release Builds

on:
  push:
    paths:
      - '**.sh'
      - '**.yml'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/create-archives.sh
        id: create-archives
      - uses: actions/create-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create-archives.outputs.version }}
          release_name: ${{ steps.create-archives.outputs.version }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ steps.create-archives.outputs.linux-path }}
          asset_name: ${{ steps.create-archives.outputs.linux-path }}
          asset_content_type: application/octet-stream
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ steps.create-archives.outputs.win32-path }}
          asset_name: ${{ steps.create-archives.outputs.win32-path }}
          asset_content_type: application/octet-stream
