name: tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 8

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - run: sudo sysctl net.ipv4.tcp_fin_timeout=30
      - uses: actions/checkout@v2
      - name: Run FedericoCarboni/setup-ffmpeg
        uses: ./
      - name: Run FedericoCarboni/setup-ffmpeg
        id: setup-ffmpeg
        uses: ./
      - run: echo ${{ steps.setup-ffmpeg.outputs.ffmpeg-path }} ${{ steps.setup-ffmpeg.outputs.ffprobe-path }}
      - run: ffmpeg -version
      - run: ffprobe -version
