name: tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: FedericoCarboni/setup-ffmpeg
        uses: ./
      - name: FedericoCarboni/setup-ffmpeg
        id: setup-ffmpeg
        uses: ./
      - run: echo ${{ steps.setup-ffmpeg.outputs.ffmpeg-path }} ${{ steps.setup-ffmpeg.outputs.ffprobe-path }}
      - run: ffmpeg -version
      - run: ffprobe -version
