name: tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 2

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Run FedericoCarboni/setup-ffmpeg
        uses: ./
      - name: Run FedericoCarboni/setup-ffmpeg
        id: setup-ffmpeg
        uses: ./
      - run: ffmpeg -version
      - run: ffprobe -version
